// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "iphone-16-pro": {
      name: "iphone-16-pro",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/mockup/iphone-16-pro.tsx"],
      component: React.lazy(() => import("@/registry/default/designali/mockup/iphone-16-pro.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-blockquote": {
      name: "typography-blockquote",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-blockquote.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-blockquote.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-demo": {
      name: "typography-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h1": {
      name: "typography-h1",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-h1.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-h1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h2": {
      name: "typography-h2",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-h2.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-h2.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h3": {
      name: "typography-h3",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-h3.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-h3.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h4": {
      name: "typography-h4",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-h4.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-h4.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-inline-code": {
      name: "typography-inline-code",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-inline-code.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-inline-code.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-large": {
      name: "typography-large",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-large.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-large.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-lead": {
      name: "typography-lead",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-lead.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-lead.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-list": {
      name: "typography-list",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-list.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-list.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-muted": {
      name: "typography-muted",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-muted.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-muted.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-p": {
      name: "typography-p",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-p.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-p.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-small": {
      name: "typography-small",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-small.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-small.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-table": {
      name: "typography-table",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-table.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-table.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
