// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "button": {
      name: "button",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/ui/button.tsx"],
      component: React.lazy(() => import("@/registry/default/designali/ui/button.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tabs": {
      name: "tabs",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/ui/tabs.tsx"],
      component: React.lazy(() => import("@/registry/default/designali/ui/tabs.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "safari": {
      name: "safari",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/mockups/safari.tsx"],
      component: React.lazy(() => import("@/registry/default/designali/mockups/safari.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ipad-pro": {
      name: "ipad-pro",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/mockups/ipad-pro.tsx"],
      component: React.lazy(() => import("@/registry/default/designali/mockups/ipad-pro.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "macbook-pro": {
      name: "macbook-pro",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/mockups/macbook-pro.tsx"],
      component: React.lazy(() => import("@/registry/default/designali/mockups/macbook-pro.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "mac": {
      name: "mac",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/mockups/mac.tsx"],
      component: React.lazy(() => import("@/registry/default/designali/mockups/mac.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "iphone-16": {
      name: "iphone-16",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/mockups/iphone-16.tsx"],
      component: React.lazy(() => import("@/registry/default/designali/mockups/iphone-16.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "iphone-16-pro": {
      name: "iphone-16-pro",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/mockups/iphone-16-pro.tsx"],
      component: React.lazy(() => import("@/registry/default/designali/mockups/iphone-16-pro.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-blockquote": {
      name: "typography-blockquote",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-blockquote.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-blockquote.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-demo": {
      name: "typography-demo",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h1": {
      name: "typography-h1",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-h1.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-h1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h2": {
      name: "typography-h2",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-h2.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-h2.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h3": {
      name: "typography-h3",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-h3.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-h3.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h4": {
      name: "typography-h4",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-h4.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-h4.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-inline-code": {
      name: "typography-inline-code",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-inline-code.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-inline-code.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-large": {
      name: "typography-large",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-large.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-large.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-lead": {
      name: "typography-lead",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-lead.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-lead.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-list": {
      name: "typography-list",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-list.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-list.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-muted": {
      name: "typography-muted",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-muted.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-muted.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-p": {
      name: "typography-p",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-p.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-p.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-small": {
      name: "typography-small",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-small.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-small.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-table": {
      name: "typography-table",
      type: "registry:example",
      registryDependencies: undefined,
      files: ["registry/default/example/typography-table.tsx"],
      component: React.lazy(() => import("@/registry/default/example/typography-table.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-01": {
      name: "button-01",
      type: "registry:components",
      registryDependencies: undefined,
      files: ["registry/default/components/buttons/button-01.tsx"],
      component: React.lazy(() => import("@/registry/default/components/buttons/button-01.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-02": {
      name: "button-02",
      type: "registry:components",
      registryDependencies: undefined,
      files: ["registry/default/components/buttons/button-02.tsx"],
      component: React.lazy(() => import("@/registry/default/components/buttons/button-02.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-03": {
      name: "button-03",
      type: "registry:components",
      registryDependencies: undefined,
      files: ["registry/default/components/buttons/button-03.tsx"],
      component: React.lazy(() => import("@/registry/default/components/buttons/button-03.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-04": {
      name: "button-04",
      type: "registry:components",
      registryDependencies: undefined,
      files: ["registry/default/components/buttons/button-04.tsx"],
      component: React.lazy(() => import("@/registry/default/components/buttons/button-04.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-05": {
      name: "button-05",
      type: "registry:components",
      registryDependencies: undefined,
      files: ["registry/default/components/buttons/button-05.tsx"],
      component: React.lazy(() => import("@/registry/default/components/buttons/button-05.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "safari-1": {
      name: "safari-1",
      type: "registry:components",
      registryDependencies: undefined,
      files: ["registry/default/components/mockups/safari-1.tsx"],
      component: React.lazy(() => import("@/registry/default/components/mockups/safari-1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "macbook-pro-1": {
      name: "macbook-pro-1",
      type: "registry:components",
      registryDependencies: undefined,
      files: ["registry/default/components/mockups/macbook-pro-1.tsx"],
      component: React.lazy(() => import("@/registry/default/components/mockups/macbook-pro-1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "mac-1": {
      name: "mac-1",
      type: "registry:components",
      registryDependencies: undefined,
      files: ["registry/default/components/mockups/mac-1.tsx"],
      component: React.lazy(() => import("@/registry/default/components/mockups/mac-1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ipad-pro-1": {
      name: "ipad-pro-1",
      type: "registry:components",
      registryDependencies: undefined,
      files: ["registry/default/components/mockups/ipad-pro-1.tsx"],
      component: React.lazy(() => import("@/registry/default/components/mockups/ipad-pro-1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "iphone-16-pro-1": {
      name: "iphone-16-pro-1",
      type: "registry:components",
      registryDependencies: undefined,
      files: ["registry/default/components/mockups/iphone-16-pro-1.tsx"],
      component: React.lazy(() => import("@/registry/default/components/mockups/iphone-16-pro-1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
