// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "iphone-16-pro": {
      name: "iphone-16-pro",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/mockup/iphone-16-pro.tsx"],
      component: React.lazy(() => import("@/registry/default/designali/mockup/iphone-16-pro.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
