/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import type { DesignaliIcon } from "dicons";
import {
  Accessibility,
  Baby,
  BadgeHelp,
  BadgeInfo,
  CircleHelp,
  Contrast,
  Ear,
  EarOff,
  Eclipse,
  Eye,
  EyeOff,
  Glasses,
  Hand,
  Info,
  LifeBuoy,
  Moon,
  MoonStar,
  PersonStanding,
  ScanEye,
  ScanSearch,
  Speech,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  ZoomIn,
  ZoomOut,
} from "dicons";

export type DIcon = DesignaliIcon;

export type ValidIcon = keyof typeof Access;

export const Access = {
  Accessibility: Accessibility,
  Baby: Baby,
  BadgeHelp: BadgeHelp,
  BadgeInfo: BadgeInfo,
  CircleHelp: CircleHelp,
  Contrast: Contrast,
  Ear: Ear,
  EarOff: EarOff,
  Eclipse: Eclipse,
  Eye: Eye,
  EyeOff: EyeOff,
  Glasses: Glasses,
  Hand: Hand,
  Info: Info,
  LifeBuoy: LifeBuoy,
  Moon: Moon,
  MoonStar: MoonStar,
  PersonStanding: PersonStanding,
  ScanEye: ScanEye,
  ScanSearch: ScanSearch,
  Speech: Speech,
  Sun: Sun,
  SunDim: SunDim,
  SunMedium: SunMedium,
  SunMoon: SunMoon,
  ZoomIn: ZoomIn,
  ZoomOut: ZoomOut,
};
