/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import type { DesignaliIcon } from "dicons";
import {
  ChartArea,
  ChartBar,
  ChartBarBig,
  ChartBarDecreasing,
  ChartBarIncreasing,
  ChartBarStacked,
  ChartCandlestick,
  ChartColumn,
  ChartColumnBig,
  ChartColumnDecreasing,
  ChartColumnIncreasing,
  ChartColumnStacked,
  ChartLine,
  ChartNetwork,
  ChartNoAxesColumn,
  ChartNoAxesColumnDecreasing,
  ChartNoAxesColumnIncreasing,
  ChartNoAxesCombined,
  ChartNoAxesGantt,
  ChartPie,
  ChartScatter,
  ChartSpline,
  FolderKanban,
  Kanban,
  PanelsTopLeft,
  SquareChartGantt,
  SquareDashedKanban,
  SquareKanban,
  TrendingDown,
  TrendingUp,
} from "dicons";

export type DIcon = DesignaliIcon;

export type ValidIcon = keyof typeof DCharts;

export const DCharts = {
  ChartArea,
  ChartBar,
  ChartBarBig,
  ChartBarDecreasing,
  ChartBarIncreasing,
  ChartBarStacked,
  ChartCandlestick,
  ChartColumn,
  ChartColumnBig,
  ChartColumnDecreasing,
  ChartColumnIncreasing,
  ChartColumnStacked,
  ChartLine,
  ChartNetwork,
  ChartNoAxesColumn,
  ChartNoAxesColumnDecreasing,
  ChartNoAxesColumnIncreasing,
  ChartNoAxesCombined,
  ChartNoAxesGantt,
  ChartPie,
  ChartScatter,
  ChartSpline,
  FolderKanban,
  Kanban,
  PanelsTopLeft,
  SquareChartGantt,
  SquareDashedKanban,
  SquareKanban,
  TrendingDown,
  TrendingUp,
};
