import React from "react";
import {
  Album,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Box,
  Calendar,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronUp,
  CircleCheck,
  Command,
  Equal,
  Eye,
  Github,
  Image,
  Instagram,
  Link,
  List,
  Loader,
  LogIn,
  LogOut,
  Mail,
  Maximize,
  Minus,
  Moon,
  MoveDiagonal,
  Phone,
  Redo,
  Repeat,
  Send,
  Shapes,
  Share2,
  ShoppingBag,
  SquarePen,
  Star,
  Sun,
  SwatchBook,
  Trash,
  Undo,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

import type { DesignaliIcon, DesignaliProps } from "./types";
import {
  AlignLeft,
  Circle,
  Copy,
  Download,
  Plus,
  Search,
  Shuffle,
} from "./icons";

export type DIcon = DesignaliIcon;

export type ValidIcon = keyof typeof DIcons;

export const DIcons = {
  image: Image,
  repeat: Repeat,
  trash: Trash,
  upload: Upload,
  shuffle: Shuffle,
  undo: Undo,
  redo: Redo,
  pen: SquarePen,
  star: Star,
  link: Link,
  badge: BadgeCheck,
  share: Share2,
  calendar: Calendar,
  list: List,
  eye: Eye,
  album: Album,
  movediag: MoveDiagonal,
  checkcircle: CircleCheck,
  box: Box,
  ismage: Image,
  repseat: Repeat,
  trsash: Trash,
  upsload: Upload,
  shsuffle: Shuffle,
  unsdo: Undo,
  resdo: Redo,
  pesn: SquarePen,
  stsar: Star,
  lisnk: Link,
  basdge: BadgeCheck,
  shsare: Share2,
  caslendar: Calendar,
  lisst: List,
  eyse: Eye,
  alsbum: Album,
  imfage: Image,
  refpeat: Repeat,
  trfash: Trash,
  upfload: Upload,
  shfuffle: Shuffle,
  unfdo: Undo,
  refdo: Redo,
  pefn: SquarePen,
  stfar: Star,
  lifnk: Link,
  upsqload: Upload,
  shsquffle: Shuffle,
  unsqdo: Undo,
  reqsdo: Redo,
  peqsn: SquarePen,
  stsqar: Star,
  lisqnk: Link,
  basqdge: BadgeCheck,
  shsqare: Share2,
  casqlendar: Calendar,
  lisqst: List,
  eysqe: Eye,
  alsqbum: Album,
  imfqage: Image,
  refqpeat: Repeat,
  trfqqash: Trash,
  upqfload: Upload,
  shqfuffle: Shuffle,
  unqfdo: Undo,
  reqfdo: Redo,
  peqfn: SquarePen,
  stqqfar: Star,
  lifqnk: Link,
  upwsload: Upload,
  shswuffle: Shuffle,
  unswdo: Undo,
  reswdo: Redo,
  peswn: SquarePen,
  stswar: Star,
  liswnk: Link,
  bawsdge: BadgeCheck,
  shware: Share2,
  caswlendar: Calendar,
  liwwsst: List,
  eywe: Eye,
  alwsbum: Album,
  imwfage: Image,
  refwpeat: Repeat,
  trfwash: Trash,
  upfwload: Upload,
  shfwuffle: Shuffle,
  unfwdo: Undo,
  refwdo: Redo,
  pefwn: SquarePen,
  stfwar: Star,
  liwfnk: Link,
  bafdge: BadgeCheck,
  shfare: Share2,
  caflendar: Calendar,
  lifst: List,
  eyfe: Eye,
  alfbum: Album,
  movfediag: MoveDiagonal,
  checfkcircle: CircleCheck,
  bofx: Box,
  imaage: Image,
  reapeat: Repeat,
  tarash: Trash,
  upaload: Upload,
  shauffle: Shuffle,
  unaado: Undo,
  reado: Redo,
  pean: SquarePen,
  staar: Star,
  linak: Link,
  badage: BadgeCheck,
  shaare: Share2,
  caalendar: Calendar,
  liast: List,
  eyae: Eye,
  alabum: Album,
  imgage: Image,
  repgeat: Repeat,
  trgash: Trash,
  upgload: Upload,
  shguffle: Shuffle,
  ungdo: Undo,
  regdo: Redo,
  pegn: SquarePen,
  stgar: Star,
  lignk: Link,
  bagdge: BadgeCheck,
  shgare: Share2,
  caglendar: Calendar,
  ligst: List,
  eyge: Eye,
  algbum: Album,
  movgediag: MoveDiagonal,
  chegckcircle: CircleCheck,
  bogx: Box,
  movaediag: MoveDiagonal,
  checakcircle: CircleCheck,
  boax: Box,
  mosvediag: MoveDiagonal,
  chesckcircle: CircleCheck,
  bosx: Box,
  chevrondown: ChevronDown,
  chevronup: ChevronUp,
  checkcheck: CheckCheck,
  minus: Minus,
  check: Check,
  send: Send,
  loader: Loader,
  github: Github,
  shoppingbag: ShoppingBag,
  gradient: SwatchBook,
  zoomin: ZoomIn,
  zoomout: ZoomOut,
  maximize: Maximize,
  moon: Moon,
  sun: Sun,
  plus: Plus,
  command: Command,
  search: Search,
  copy: Copy,
  download: Download,
  login: LogIn,
  logout: LogOut,
  shapes: Shapes,
  arrowright: ArrowRight,
  arrowup: ArrowUp,
  mail: Mail,
  phone: Phone,
  close: X,
  menu: Equal,
  instagram: Instagram,
  Copy: Copy,
  Plus: Plus,
  Download: Download,
  Circle: Circle,
  Shuffle: Shuffle,
  Search: Search,
  AlignLeft: AlignLeft,
  heart: ({ ...props }: DesignaliProps) => (
    <svg
      aria-hidden="true"
      focusable="false"
      data-prefix="fab"
      data-icon="heart"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 205.18 156.34"
      {...props}
    >
      <path
        fill="currentColor"
        d="M102.38,33.66c3.14-4.85,5.82-9.75,9.22-14.1,7.83-10.01,18.16-16.19,30.73-18.32,12.49-2.12,24.76-1.29,36.21,4.51,13.93,7.06,22.26,18.56,25.34,33.85,1.9,9.41,1.69,18.82-.42,28.18-2.51,11.12-8.64,19.81-17.73,26.55-8.89,6.59-18.89,11.1-28.91,15.58-10.02,4.47-19.96,9.09-29.11,15.24-11.03,7.42-19.98,16.48-24.22,29.46-.15,.47-.39,.91-.75,1.74-.56-1.16-1.09-2.03-1.41-2.97-4.17-12.37-12.98-20.86-23.41-27.98-10.7-7.31-22.46-12.53-34.3-17.65-9.47-4.09-18.57-8.88-26.76-15.31C7.56,85.11,2.78,75.33,.98,63.98c-1.6-10.1-1.38-20.19,1.8-30.06C7.47,19.38,16.95,9.11,31.15,3.8c13.86-5.18,28.06-5.05,41.92,.32,12.14,4.7,20.75,13.52,26.93,24.82,.87,1.59,1.64,3.23,2.39,4.72Z"
      ></path>
    </svg>
  ),
};
