export default function Home() {
  return (
    <main className="mt-4">
      <div className="mx-auto max-w-3xl lg:max-w-6xl">
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-2">
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279277/creatives/vid/3_likg2t.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279220/creatives/vid/2_kol6av.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279218/creatives/vid/4_jpzscs.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279197/creatives/vid/1_axo8ke.mp4"
            }
          />
        </div>
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-3">
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279217/creatives/vid/060_ltzuhh.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279199/creatives/vid/056_mmonti.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279196/creatives/vid/052_tnc6k1.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279190/creatives/vid/011_h43bab.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279190/creatives/vid/02_wrqra7.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279190/creatives/vid/09_bzk3q2.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279186/creatives/vid/01_biln5v.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279185/creatives/vid/04_t760xh.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279183/creatives/vid/025_tvpe2h.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279183/creatives/vid/048_u14cdg.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279183/creatives/vid/08_mmhcn9.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279183/creatives/vid/053_vqevwo.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279181/creatives/vid/051_bmy5ic.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279181/creatives/vid/016_hdkwxl.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279180/creatives/vid/013_iowkks.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279180/creatives/vid/014_aebxmd.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279180/creatives/vid/029_jtj3qj.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279179/creatives/vid/015_na74dz.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279178/creatives/vid/055_k5jwdq.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279178/creatives/vid/03_r8mbrm.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279178/creatives/vid/07_f0fbox.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279178/creatives/vid/054_jmj06s.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279177/creatives/vid/058_w5ns29.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279177/creatives/vid/010_yqyq45.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279176/creatives/vid/05_fs6kgb.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279176/creatives/vid/049_vqauco.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279176/creatives/vid/06_olm3sg.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279175/creatives/vid/057_l2usrw.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279175/creatives/vid/012_cbjygg.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279174/creatives/vid/041_hi0uta.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279174/creatives/vid/038_ltx4nf.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279174/creatives/vid/050_i7kdh6.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279174/creatives/vid/045_j6hil2.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279174/creatives/vid/042_f0kz2w.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279173/creatives/vid/046_e4v249.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279173/creatives/vid/030_bzlr36.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279172/creatives/vid/059_uiulcl.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279172/creatives/vid/026_rdserl.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279172/creatives/vid/039_ztxo2v.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279171/creatives/vid/040_auwy7k.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279170/creatives/vid/043_xgthdf.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279170/creatives/vid/047_vdi9qs.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279170/creatives/vid/031_ypddbt.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279169/creatives/vid/033_ddqq0y.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279169/creatives/vid/018_vwpdrt.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279169/creatives/vid/019_lhuffh.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279168/creatives/vid/037_ytlmfq.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279168/creatives/vid/034_nva5gk.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279168/creatives/vid/027_gxphp2.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279168/creatives/vid/036_hef0mm.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279168/creatives/vid/020_fdcwqq.mp4"
            }
          />
        </div>
      </div>
    </main>
  );
}
