import type { Registry } from "@/registry/schema";

export const ui: Registry = [
  // UI
  {
    name: "Sidebar",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/sidebar.tsx"],
  },
  {
    name: "accordion",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/accordion.tsx"],
  },
  {
    name: "alert-dialog",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/alert-dialog.tsx"],
  },
  {
    name: "alert",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/alert.tsx"],
  },
  {
    name: "aspect-ratio",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/aspect-ratio.tsx"],
  },
  {
    name: "avatar",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/avatar.tsx"],
  },
  {
    name: "badge",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/badge.tsx"],
  },
  {
    name: "breadcrumb",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/breadcrumb.tsx"],
  },
  {
    name: "button",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/button.tsx"],
  },
  {
    name: "calendar",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/calendar.tsx"],
  },
  {
    name: "card",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/card.tsx"],
  },
  {
    name: "carousel",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/carousel.tsx"],
  },
  {
    name: "checkbox",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/checkbox.tsx"],
  },
  {
    name: "combobox",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/combobox.tsx"],
  },
  {
    name: "collapsible",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/collapsible.tsx"],
  },
  {
    name: "command",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/command.tsx"],
  },
  {
    name: "date-picker",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/date-picker.tsx"],
  },
  {
    name: "dialog",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/dialog.tsx"],
  },
  {
    name: "drawer",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/drawer.tsx"],
  },
  {
    name: "dropdown-menu",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/dropdown-menu.tsx"],
  },
  {
    name: "form",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/form.tsx"],
  },
  {
    name: "hover-card",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/hover-card.tsx"],
  },
  {
    name: "mode-toggle",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/mode-toggle.tsx"],
  },
  {
    name: "navigation-menu",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/navigation-menu.tsx"],
  },
  {
    name: "pagination",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/pagination.tsx"],
  },
  {
    name: "popover",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/popover.tsx"],
  },
  {
    name: "progress",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/progress.tsx"],
  },
  {
    name: "radio-group",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/radio-group.tsx"],
  },
  {
    name: "resizable",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/resizable.tsx"],
  },
  {
    name: "scroll-area",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/scroll-area.tsx"],
  },
  {
    name: "select",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/select.tsx"],
  },
  {
    name: "separator",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/separator.tsx"],
  },
  {
    name: "sheet",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/sheet.tsx"],
  },
  {
    name: "skeleton",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/skeleton.tsx"],
  },
  {
    name: "slider",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/slider.tsx"],
  },
  {
    name: "sonner",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/sonner.tsx"],
  },
  {
    name: "switch",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/switch.tsx"],
  },
  {
    name: "table",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/table.tsx"],
  },
  {
    name: "tabs",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/tabs.tsx"],
  },
  {
    name: "textarea",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/textarea.tsx"],
  },
  {
    name: "toast",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/toast.tsx"],
  },
  {
    name: "toasts",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/toasts.tsx"],
  },
  {
    name: "toaster",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/toaster.tsx"],
  },
  {
    name: "toggle",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/toggle.tsx"],
  },
  {
    name: "toggle-group",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/toggle-group.tsx"],
  },
  {
    name: "tooltip",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/ui/tooltip.tsx"],
  },
  // Safari
  {
    name: "safari",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/mockups/safari.tsx"],
  },
  // Safari
  {
    name: "ipad-pro",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/mockups/ipad-pro.tsx"],
  },
  // Macbook
  {
    name: "macbook-pro",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/mockups/macbook-pro.tsx"],
  },
  // iMac
  {
    name: "mac",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/mockups/mac.tsx"],
  },
  // iPhone
  {
    name: "iphone-16",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/mockups/iphone-16.tsx"],
  },
  {
    name: "iphone-16-pro",
    type: "registry:ui",
    dependencies: [""],
    files: ["designali/mockups/iphone-16-pro.tsx"],
  },
];
