// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  default: {
    typo: {
      name: "typo",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/designali/typography-h1.tsx"],
      component: React.lazy(
        () => import("@/registry/default/designali/typography-h1.tsx"),
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    utils: {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
  },
};
