export default function Home() {
  return (
    <main className="mt-4">
      <div className="mx-auto max-w-3xl lg:max-w-6xl">
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-3">
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279187/creatives/reels/00_d8bech.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279208/creatives/reels/08_mvg5h4.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279207/creatives/reels/013_hlbvas.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279205/creatives/reels/02_uk15hb.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279199/creatives/reels/06_eviwcm.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279191/creatives/reels/05_pn5czc.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279189/creatives/reels/01_uperzv.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279188/creatives/reels/012_wtq2dx.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279187/creatives/reels/04_qyyiwb.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279186/creatives/reels/07_wfyd5k.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279186/creatives/reels/09_lpbgv4.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279183/creatives/reels/016_ehachw.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279180/creatives/reels/015_ngtqoj.mp4"
            }
          />
          <video
            controls
            width="auto"
            height={320}
            src={
              "https://res.cloudinary.com/dfyfxr10u/video/upload/v1723279176/creatives/reels/014_mfjhge.mp4"
            }
          />
        </div>
      </div>
    </main>
  );
}
